#file: noinspection SpellCheckingInspection
site_name: Jankson Wiki
repo_url: https://github.com/falkreon/Jankson
edit_uri: edit/main/docs/
repo_name: Jankson
theme:
  name: material
  favicon: images/jankson.png
  logo: images/jankson.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - content.tabs.link
    - content.action.edit
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["docs"]
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home:
      - 'index.md'
      - "Getting Started": 'getting_started.md'
      - "Quirks": 'quirks.md'
  - 1.2.x:
      - "Loading POJOs": "v1/loading_pojos.md"
      - "Combine with Gson/Jackson": "v1/jankson_preprocessor.md"
      - "Custom (De)serializers": "v1/custom_serialization.md"
