name: Deploy Docs
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy_mkdocs.yml"
      - "docs/**"
      - "mkdocs.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: MkDocs Deployment
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
